SELECT
    JBXX0.ENTID
    , JBXX0.DISTRICT
    , BG0.ALTBE
    , BG0.ALTAF
    , BG0.ALTDATE
FROM CDB_NOV.F_QY_JBXX JBXX0
LEFT JOIN CDB_NOV.F_QY_BG BG0
ON JBXX0.ENTID = BG0.ENTID
WHERE {where_district_str} --筛选省码或者市码
AND BG0.ALTITEM = '30'
AND (BG0.ALTAF IS NOT NULL OR BG0.ALTBE IS NOT NULL)